To do list enhancements
rainrivas/toDoList pull request #1
Opened 2017-07-09 06:22 UTC by jwu910

I think this should be every non-destructive change i've made to your base code. Current notable enhancements are auto focusing on input as you click add new item. Restrictions that do not add blank entries to list. and a Clear All items button.

2017-07-09 06:32 UTC, rainrivas requested changes
Correct boostrap css declaration.

2017-07-09 06:32 UTC, rainrivas commented on index.html
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin
You'll need to move the bootstrap CSS to be BEFORE the custom CSS or else the boot strap styles will be applied over custom ones.

2017-07-09 06:42 UTC, jwu910 commented
I moved it, and removed the send to phone button. Also added tab index 0 to icon for future keyboard accessibility.

2017-07-09 06:49 UTC, rainrivas approved these changes
Looks good, not too worried about losing strike through here since we'll just be deleting items we finish

2017-07-09 06:50 UTC, merged

2017-07-10 01:42 UTC, jwu910 commented
Good stuff, thanks!